pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building the project'
		bat 'mvn clean'
            }
        }
   
        stage('Test') {
            steps {
                echo 'Testing the project'
		bat 'mvn test'
            }
        }
	stage('Compile') {
            steps {
                echo 'Compile the project'
		bat 'mvn compile'
            }
        }
 
        stage('Deploy') {
            steps {
                echo 'Deploy the project'
            }
        }
    }
}
